name: SAST - Semgrep Security Scan
on:
  workflow_dispatch:
  pull_request:
  workflow_call:

permissions:
  contents: read
  pull-requests: write

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Semgrep Scan
        id: scan
        run: |
          semgrep scan \
            --config=auto \
            --severity ERROR \
            --error \
            --use-git-ignore 2>&1 | tee semgrep-results.txt
        continue-on-error: true

      - name: Display results
        if: always()
        run: |
          echo "## Semgrep Security Scan Results"
          cat semgrep-results.txt

      - name: Process Results
        if: always()
        id: results
        run: |
          echo "## Semgrep Security Scan Results" >> $GITHUB_STEP_SUMMARY
          cat semgrep-results.txt >> $GITHUB_STEP_SUMMARY
          cat semgrep-results.txt >> $GITHUB_OUTPUT

      - name: Comment PR
        if: github.event_name == 'pull_request' && always()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const results = fs.readFileSync('semgrep-results.txt', 'utf8');

            const output = `
            #### Semgrep Scan Results
            \`\`\`
            ${results}
            \`\`\`
            `;

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });

      - name: Upload Scan Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-results
          path: |
            semgrep-results.txt
