name: SCA - Trivy Vulnerability Scan
on:
  workflow_dispatch:
  pull_request:
  workflow_call:

jobs:
  trivy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: .
          scanners: vuln
          format: 'table'
          exit-code: '1'
          output: 'trivy-results.txt'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true

      - name: Add to Job Summary
        if: always()
        run: |
          echo "## Trivy Security Scan Results" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          cat trivy-results.txt >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

      - name: Set output variables
        if: github.event_name == 'pull_request' && always()
        id: vars
        run: |
          REPORT="$(cat trivy-results.txt)"
          echo "report<<EOF" >> $GITHUB_OUTPUT
          echo "$REPORT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Comment PR
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request' && always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `
            #### Trivy Scan Results
            \`\`\`
            ${process.env.REPORT}
            \`\`\`
            `;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
        env:
          REPORT: ${{ steps.vars.outputs.report }}

      - name: Upload Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-results.txt
