name: Container Scan - All
on:
  workflow_dispatch:
  # pull_request:

jobs:
  container-dockle:
    uses: ./.github/workflows/Container-Dockle.yml
  container-trivy:
    uses: ./.github/workflows/Container-Trivy.yml
