name: Secrets Scan - All
on:
  workflow_dispatch:
  # pull_request:

jobs:
  secrets-gitleaks:
    uses: ./.github/workflows/Secrets-Gitleaks.yml
  secrets-trufflehog:
    uses: ./.github/workflows/Secrets-TruffleHog.yml
  secrets-ggshield:
    uses: ./.github/workflows/Secrets-GGShield.yml
