name: Security Scan - All

on:
  workflow_dispatch:
  # pull_request:

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  secrets-gitleaks:
    uses: ./.github/workflows/Secrets-Gitleaks.yml
    secrets: inherit
    permissions:
      contents: read
      pull-requests: write
      security-events: write
  secrets-trufflehog:
    uses: ./.github/workflows/Secrets-TruffleHog.yml
    secrets: inherit
    permissions:
      contents: read
      pull-requests: write
      security-events: write
  secrets-ggshield:
    uses: ./.github/workflows/Secrets-GGShield.yml
    secrets: inherit
    permissions:
      contents: read
      pull-requests: write
      security-events: write

  sca-depcheck:
    uses: ./.github/workflows/SCA-Dependency-Check.yml
    secrets: inherit
    permissions:
      contents: read
      pull-requests: write
      security-events: write
  sca-trivy:
    uses: ./.github/workflows/SCA-Trivy.yml
    secrets: inherit
    permissions:
      contents: read
      pull-requests: write
      security-events: write
  sca-grype:
    uses: ./.github/workflows/SCA-Grype.yml
    secrets: inherit
    permissions:
      contents: read
      pull-requests: write
      security-events: write

  sast-semgrep:
    uses: ./.github/workflows/SAST-Semgrep.yml
    secrets: inherit
    permissions:
      contents: read
      pull-requests: write
      security-events: write
  sast-codeql:
    uses: ./.github/workflows/SAST-CodeQL.yml
    secrets: inherit
    permissions:
      contents: read
      pull-requests: write
      security-events: write

  container-dockle:
    uses: ./.github/workflows/Container-Dockle.yml
    secrets: inherit
    permissions:
      contents: read
      pull-requests: write
      security-events: write
  container-trivy:
    uses: ./.github/workflows/Container-Trivy.yml
    secrets: inherit
    permissions:
      contents: read
      pull-requests: write
      security-events: write
