name: Secrets Scan - All

on:
  workflow_dispatch:
  # pull_request:
  #   branches:
  #     - main

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  secrets-gitleaks:
    uses: ./.github/workflows/Secrets-Gitleaks.yml
  secrets-trufflehog:
    uses: ./.github/workflows/Secrets-TruffleHog.yml
  secrets-ggshield:
    uses: ./.github/workflows/Secrets-GGShield.yml
    secrets: inherit
