name: SAST Scan - All

on:
  workflow_dispatch:
  # pull_request:
  #   branches:
  #     - main

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  sast-semgrep:
    uses: ./.github/workflows/SAST-Semgrep.yml
    secrets: inherit
    permissions:
      contents: read
      pull-requests: write
      security-events: write
  sast-codeql:
    uses: ./.github/workflows/SAST-CodeQL.yml
    secrets: inherit
    permissions:
      contents: read
      pull-requests: write
      security-events: write
