name: SCA Scan - All

on:
  workflow_dispatch:
  # pull_request:
  #   branches:
  #     - main

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  sca-depcheck:
    uses: ./.github/workflows/SCA-Dependency-Check.yml
    secrets: inherit
  sca-trivy:
    uses: ./.github/workflows/SCA-Trivy.yml
    secrets: inherit
  sca-grype:
    uses: ./.github/workflows/SCA-Grype.yml
    secrets: inherit
