name: Secrets Scan - All
on:
  workflow_dispatch:
  # pull_request:

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  secrets-gitleaks:
    uses: ./.github/workflows/Secrets-Gitleaks.yml
    permissions:
      contents: read
      pull-requests: write
      security-events: write
  secrets-trufflehog:
    uses: ./.github/workflows/Secrets-TruffleHog.yml
    permissions:
      contents: read
      pull-requests: write
      security-events: write
  secrets-ggshield:
    uses: ./.github/workflows/Secrets-GGShield.yml
    secrets: inherit
    permissions:
      contents: read
      pull-requests: write
      security-events: write
