name: Secrets Scan - All
on:
  workflow_dispatch:
  # pull_request:

jobs:
  sca-depcheck:
    uses: ./.github/workflows/SCA-Dependency-Check.yml
  sca-trivy:
    uses: ./.github/workflows/SCA-Trivy.yml
  sca-grype:
    uses: ./.github/workflows/SCA-Grype.yml
