name: Container Scan - All
on:
  workflow_dispatch:
  # pull_request:

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  container-dockle:
    uses: ./.github/workflows/Container-Dockle.yml
    secrets: inherit
    permissions:
      contents: read
      pull-requests: write
      security-events: write
  container-trivy:
    uses: ./.github/workflows/Container-Trivy.yml
    secrets: inherit
    permissions:
      contents: read
      pull-requests: write
      security-events: write
