name: Security Scan - All

on:
  workflow_dispatch:
  # pull_request:
  #   branches:
  #     - main

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  secrets-gitleaks:
    uses: ./.github/workflows/Secrets-Gitleaks.yml
    secrets: inherit
  secrets-trufflehog:
    uses: ./.github/workflows/Secrets-TruffleHog.yml
    secrets: inherit
  secrets-ggshield:
    uses: ./.github/workflows/Secrets-GGShield.yml
    secrets: inherit

  sca-depcheck:
    uses: ./.github/workflows/SCA-Dependency-Check.yml
    secrets: inherit
  sca-trivy:
    uses: ./.github/workflows/SCA-Trivy.yml
    secrets: inherit
  sca-grype:
    uses: ./.github/workflows/SCA-Grype.yml
    secrets: inherit

  sast-semgrep:
    uses: ./.github/workflows/SAST-Semgrep.yml
    secrets: inherit
  sast-codeql:
    uses: ./.github/workflows/SAST-CodeQL.yml
    secrets: inherit

  container-dockle:
    uses: ./.github/workflows/Container-Dockle.yml
    secrets: inherit
  container-trivy:
    uses: ./.github/workflows/Container-Trivy.yml
    secrets: inherit
