name: Secrets - Gitleaks Scan
on:
  workflow_dispatch:
  pull_request:
  workflow_call:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch full commit history for a complete scan
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: '--verbose --report-format=json --report-path=gitleaks-report.json' # Run Gitleaks with verbose output, JSON format, and save report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Gitleaks Report
        # Ensure this step runs even if the scan fails
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json
