name: Secrets - GitGuardian CLI Scan
on:
  workflow_dispatch:
  pull_request:
  workflow_call:

jobs:
  ggshield:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install GitGuardian CLI
        run: pip install ggshield
      - name: Run GitGuardian CLI Scan
        env:
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
        run: ggshield secret scan repo .
