name: Secrets - GitGuardian Secret Scan
on:
  workflow_dispatch:
  pull_request:
  workflow_call:
    secrets:
      GITGUARDIAN_API_KEY:
        required: true

jobs:
  ggshield:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: GitGuardian scan
        id: scan
        uses: GitGuardian/ggshield/actions/secret@v1.38.0
        continue-on-error: true
        env:
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}

      - name: Add to Job Summary
        if: always()
        run: |
          echo "## GitGuardian Security Scan Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [[ "${{ steps.scan.outcome }}" == "success" ]]; then
            echo "✅ **No secrets were detected**" >> $GITHUB_STEP_SUMMARY
          else
            echo "⚠️ **Potential secrets were detected**" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "<details><summary>Click to see scan output</summary>" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            echo "${{ steps.scan.outputs.output }}" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            echo "</details>" >> $GITHUB_STEP_SUMMARY
          fi
