name: Secrets - GitGuardian CLI Scan
on:
  workflow_dispatch:
  pull_request:
  workflow_call:

jobs:
  ggshield:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: GitGuardian scan
        uses: GitGuardian/ggshield/actions/secret@v1.38.0
        env:
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
